# Copyright 2023 The WarpSpeed Authors.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//warpspeed:__subpackages__"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

load("//warpspeed:proto.bzl", "warpspeed_py_proto_library")

# warpspeed_py_proto_library(
#     name = "<filename>_proto_py_pb2",
#     srcs = ["<filename>.proto"],
# )
